add_newline = false

[line_break]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = ">"
error_symbol = "X"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[git_branch]
symbol = " "

[gcloud]
disabled = true

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

